name: Build and Send to Telegram

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Zip Package
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          zip -r "Integrity-Box-${BRANCH_NAME}.zip" . -x "*.git*" "*.github*" "assets/*" "test.zip"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Integrity-Box-Package
          path: "*.zip"

      - name: Send to Telegram
        run: |
          for file in *.zip; do
            curl -v -F document=@"$file" \
            "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument?chat_id=${{ secrets.TELEGRAM_CHAT_ID }}"
          done
