name: Build and Send to Telegram

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Zip Package
        run: |
          zip -r Integrity-Box-CN.zip . -x "*.git*" "*.github*"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Integrity-Box-CN
          path: Integrity-Box-CN.zip

      - name: Send to Telegram
        run: |
          curl -v -F document=@"Integrity-Box-CN.zip" \
          "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument?chat_id=${{ secrets.TELEGRAM_CHAT_ID }}"
